import '@module/@uswds/uswds/dist/css/uswds.min.css'
import UsaDatePickerCalendarMonth from './UsaDatePickerCalendarMonth.vue'
import { MONTH_LABELS, MIN_DATE, MAX_DATE } from '@/utils/constants.js'

describe('UsaDatePickerCalendarMonth', () => {
  it('renders the component', () => {
    const wrapperComponent = {
      components: { UsaDatePickerCalendarMonth },
      data() {
        return {
          activeDate: '2022-08-15',
          monthLabels: MONTH_LABELS,
          minDate: MIN_DATE,
          maxDate: MAX_DATE,
          activeMonth: 8,
          selectorMode: 'month',
        }
      },
      computed: {
        isOpen() {
          return this.selectorMode === 'month'
        },
        currentActiveMonth: {
          get() {
            return this.activeMonth
          },
          set(newMonth) {
            this.activeMonth = newMonth
          },
        },
        currentSelectorMode: {
          get() {
            return this.selectorMode
          },
          set(newMode) {
            this.selectorMode = newMode
          },
        },
      },
      template: `<template v-if="isOpen">
        <UsaDatePickerCalendarMonth
          :active-date="activeDate"
          :month-labels="monthLabels"
          :min-date="minDate"
          :max-date="maxDate"
          @update:selector-mode="
            newSelectorMode => (currentSelectorMode = newSelectorMode)
          "
          @update:active-month="
            selectedMonth => (currentActiveMonth = selectedMonth)
          "
        ></UsaDatePickerCalendarMonth>
      </template>`,
    }

    cy.mount(wrapperComponent, {
      global: {
        provide: {
          monthLabels: MONTH_LABELS,
        },
      },
    })

    cy.get('div.usa-date-picker__calendar__month-picker').should(
      'have.attr',
      'tabindex',
      '-1',
    )

    cy.get('table.usa-date-picker__calendar__table').should(
      'have.attr',
      'role',
      'presentation',
    )

    cy.get('.usa-date-picker__calendar__table > tbody')
      .as('table')
      .should('exist')

    cy.get('tr').should('have.length', 4)
    cy.get('td').should('have.length', 12)
    cy.get('button')
      .should('have.attr', 'type', 'button')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.class', 'usa-date-picker__calendar__month')
      .and('have.length', 12)

    cy.get('tr:nth-of-type(1) td:nth-of-type(1) button')
      .as('button1')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    cy.get('tr:nth-of-type(1) td:nth-of-type(2) button')
      .as('button2')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '2')
      .and('have.attr', 'data-label', 'February')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'February')

    cy.get('tr:nth-of-type(1) td:nth-of-type(3) button')
      .as('button3')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '3')
      .and('have.attr', 'data-label', 'March')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'March')

    cy.get('tr:nth-of-type(2) td:nth-of-type(1) button')
      .as('button4')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '4')
      .and('have.attr', 'data-label', 'April')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'April')

    cy.get('tr:nth-of-type(2) td:nth-of-type(2) button')
      .as('button5')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    cy.get('tr:nth-of-type(2) td:nth-of-type(3) button')
      .as('button6')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    cy.get('tr:nth-of-type(3) td:nth-of-type(1) button')
      .as('button7')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '7')
      .and('have.attr', 'data-label', 'July')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'July')

    cy.get('tr:nth-of-type(3) td:nth-of-type(2) button')
      .as('button8')
      .should('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('tr:nth-of-type(3) td:nth-of-type(3) button')
      .as('button9')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '9')
      .and('have.attr', 'data-label', 'September')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'September')

    cy.get('tr:nth-of-type(4) td:nth-of-type(1) button')
      .as('button10')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    cy.get('tr:nth-of-type(4) td:nth-of-type(2) button')
      .as('button11')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    cy.get('tr:nth-of-type(4) td:nth-of-type(3) button')
      .as('button12')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Up arrow key.
    cy.get('@button8').type('{upArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('have.focus')
      .and('contain', 'May')

    // Right arrow key.
    cy.get('@button5').type('{rightArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    cy.get('@button6')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    // Down arrow key.
    cy.get('@button6').type('{downArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button6')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    cy.get('@button9')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '9')
      .and('have.attr', 'data-label', 'September')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'September')

    // Hover.
    cy.get('@button12').trigger('mouseover')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button9')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '9')
      .and('have.attr', 'data-label', 'September')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'September')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Left arrow key.
    cy.get('@button12').type('{leftArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    cy.get('@button11')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    // End key.
    cy.get('@button11').type('{end}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button11')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Home key.
    cy.get('@button12').type('{home}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    cy.get('@button10')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    // End key again.
    cy.get('@button10').type('{end}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button10')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Page Up key.
    cy.get('@button12').type('{pageUp}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    cy.get('@button1')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    // Page Down key.
    cy.get('@button1').type('{pageDown}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button1')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Test focus trap.
    cy.realPress('Tab')

    cy.get('@button8')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Tab to previous focus.
    cy.realPress('Tab')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Down arrow key again.
    cy.get('@button12').type('{downArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Right arrow key again.
    cy.get('@button12').type('{rightArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Hover.
    cy.get('@button3').trigger('mouseover')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    cy.get('@button3')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '3')
      .and('have.attr', 'data-label', 'March')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'March')

    // Arrow up key.
    cy.get('@button3').type('{upArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button3')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '3')
      .and('have.attr', 'data-label', 'March')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'March')

    cy.get('@button2')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '2')
      .and('have.attr', 'data-label', 'February')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'February')

    // Arrow up again.
    cy.get('@button2').type('{upArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button2')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '2')
      .and('have.attr', 'data-label', 'February')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'February')

    cy.get('@button1')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    // Arrow up again.
    cy.get('@button1').type('{upArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button1')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    // Arrow up again.
    cy.get('@button1').type('{leftArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button1')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    // Hover.
    cy.get('@button10').trigger('mouseover')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button1')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    cy.get('@button10')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    // Arrow Down key.
    cy.get('@button10').type('{downArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button10')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    cy.get('@button11')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    // Arrow Down key.
    cy.get('@button11').type('{downArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button11')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Arrow Right key.
    cy.get('@button12').type('{rightArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Arrow Right key.
    cy.get('@button12').type('{downArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button12')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Select month.
    cy.get('@button4').click()

    cy.get('div.usa-date-picker__calendar__month-picker').should('not.exist')
  })

  it('only allows selecting months within min/max range', () => {
    cy.mount(UsaDatePickerCalendarMonth, {
      props: {
        activeDate: '2022-08-15',
        monthLabels: MONTH_LABELS,
        minDate: '2022-05-15',
        maxDate: '2022-11-15',
      },
    })

    cy.get('tr:nth-of-type(1) td:nth-of-type(1) button')
      .as('button1')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    cy.get('tr:nth-of-type(1) td:nth-of-type(2) button')
      .as('button2')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '2')
      .and('have.attr', 'data-label', 'February')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'February')

    cy.get('tr:nth-of-type(1) td:nth-of-type(3) button')
      .as('button3')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '3')
      .and('have.attr', 'data-label', 'March')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'March')

    cy.get('tr:nth-of-type(2) td:nth-of-type(1) button')
      .as('button4')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '4')
      .and('have.attr', 'data-label', 'April')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'April')

    cy.get('tr:nth-of-type(2) td:nth-of-type(2) button')
      .as('button5')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    cy.get('tr:nth-of-type(2) td:nth-of-type(3) button')
      .as('button6')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    cy.get('tr:nth-of-type(3) td:nth-of-type(1) button')
      .as('button7')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '7')
      .and('have.attr', 'data-label', 'July')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'July')

    cy.get('tr:nth-of-type(3) td:nth-of-type(2) button')
      .as('button8')
      .should('have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('tr:nth-of-type(3) td:nth-of-type(3) button')
      .as('button9')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '9')
      .and('have.attr', 'data-label', 'September')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'September')

    cy.get('tr:nth-of-type(4) td:nth-of-type(1) button')
      .as('button10')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    cy.get('tr:nth-of-type(4) td:nth-of-type(2) button')
      .as('button11')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    cy.get('tr:nth-of-type(4) td:nth-of-type(3) button')
      .as('button12')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    // Page Up key.
    cy.get('@button8').type('{pageUp}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    // Arrow Up key.
    cy.get('@button5').type('{upArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    // Arrow Left key.
    cy.get('@button5').type('{leftArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    // Home key.
    cy.get('@button5').type('{home}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    // End key.
    cy.get('@button5').type('{end}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    cy.get('@button6')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    // Home key.
    cy.get('@button6').type('{home}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button6')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    cy.get('@button5')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    // Page Down key.
    cy.get('@button5').type('{pageDown}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button5')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    cy.get('@button11')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    // Arrow Right key.
    cy.get('@button11').type('{rightArrow}')

    cy.get('@button8')
      .should('not.have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button11')
      .should('have.focus')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')
  })

  it('calendar updates to reflect new active, min, and max dates', () => {
    cy.mount(UsaDatePickerCalendarMonth, {
      props: {
        activeDate: '2022-08-15',
        monthLabels: MONTH_LABELS,
        minDate: '2022-05-15',
        maxDate: '2022-11-15',
      },
    })
      .its('wrapper')
      .as('wrapper')

    cy.get('tr:nth-of-type(1) td:nth-of-type(1) button')
      .as('button1')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    cy.get('tr:nth-of-type(1) td:nth-of-type(2) button')
      .as('button2')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '2')
      .and('have.attr', 'data-label', 'February')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'February')

    cy.get('tr:nth-of-type(1) td:nth-of-type(3) button')
      .as('button3')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '3')
      .and('have.attr', 'data-label', 'March')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'March')

    cy.get('tr:nth-of-type(2) td:nth-of-type(1) button')
      .as('button4')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '4')
      .and('have.attr', 'data-label', 'April')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'April')

    cy.get('tr:nth-of-type(2) td:nth-of-type(2) button')
      .as('button5')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    cy.get('tr:nth-of-type(2) td:nth-of-type(3) button')
      .as('button6')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    cy.get('tr:nth-of-type(3) td:nth-of-type(1) button')
      .as('button7')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '7')
      .and('have.attr', 'data-label', 'July')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'July')

    cy.get('tr:nth-of-type(3) td:nth-of-type(2) button')
      .as('button8')
      .should('have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('tr:nth-of-type(3) td:nth-of-type(3) button')
      .as('button9')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '9')
      .and('have.attr', 'data-label', 'September')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'September')

    cy.get('tr:nth-of-type(4) td:nth-of-type(1) button')
      .as('button10')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    cy.get('tr:nth-of-type(4) td:nth-of-type(2) button')
      .as('button11')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    cy.get('tr:nth-of-type(4) td:nth-of-type(3) button')
      .as('button12')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')

    cy.get('@wrapper').invoke('setProps', { activeDate: '2022-10-15' })
    cy.get('@wrapper').invoke('setProps', { minDate: '2021-02-15' })
    cy.get('@wrapper').invoke('setProps', { maxDate: '2022-10-01' })

    cy.get('@button1')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'January')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'January')

    cy.get('@button2')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '2')
      .and('have.attr', 'data-label', 'February')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'February')

    cy.get('@button3')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '3')
      .and('have.attr', 'data-label', 'March')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'March')

    cy.get('@button4')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '4')
      .and('have.attr', 'data-label', 'April')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'April')

    cy.get('@button5')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May')

    cy.get('@button6')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'June')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'June')

    cy.get('@button7')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '7')
      .and('have.attr', 'data-label', 'July')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'July')

    cy.get('@button8')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'August')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'August')

    cy.get('@button9')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '9')
      .and('have.attr', 'data-label', 'September')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'September')

    cy.get('@button10')
      .should('have.attr', 'aria-selected', 'true')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'October')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'October')

    cy.get('@button11')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'November')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'November')

    cy.get('@button12')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'disabled', 'disabled')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'December')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'December')
  })

  it('shows custom month labels', () => {
    cy.mount(UsaDatePickerCalendarMonth, {
      props: {
        activeDate: '2022-08-15',
        monthLabels: [
          'Jan1',
          'Feb2',
          'Mar3',
          'Apr4',
          'May5',
          'Jun6',
          'Jul7',
          'Aug8',
          'Sep9',
          'Oct10',
          'Nov11',
          'Dec12',
        ],
        minDate: MIN_DATE,
        maxDate: MAX_DATE,
      },
    })

    cy.get('tr').should('have.length', 4)
    cy.get('td').should('have.length', 12)

    cy.get('button')
      .should('have.attr', 'type', 'button')
      .and('not.have.attr', 'disabled', 'disabled')
      .and('have.class', 'usa-date-picker__calendar__month')
      .and('have.length', 12)

    cy.get('tr:nth-of-type(1) td:nth-of-type(1) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '1')
      .and('have.attr', 'data-label', 'Jan1')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Jan1')

    cy.get('tr:nth-of-type(1) td:nth-of-type(2) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '2')
      .and('have.attr', 'data-label', 'Feb2')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Feb2')

    cy.get('tr:nth-of-type(1) td:nth-of-type(3) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '3')
      .and('have.attr', 'data-label', 'Mar3')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Mar3')

    cy.get('tr:nth-of-type(2) td:nth-of-type(1) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '4')
      .and('have.attr', 'data-label', 'Apr4')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Apr4')

    cy.get('tr:nth-of-type(2) td:nth-of-type(2) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '5')
      .and('have.attr', 'data-label', 'May5')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'May5')

    cy.get('tr:nth-of-type(2) td:nth-of-type(3) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '6')
      .and('have.attr', 'data-label', 'Jun6')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Jun6')

    cy.get('tr:nth-of-type(3) td:nth-of-type(1) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '7')
      .and('have.attr', 'data-label', 'Jul7')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Jul7')

    cy.get('tr:nth-of-type(3) td:nth-of-type(2) button')
      .should('have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '0')
      .and('have.attr', 'data-value', '8')
      .and('have.attr', 'data-label', 'Aug8')
      .and('have.class', 'usa-date-picker__calendar__month--selected')
      .and('have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Aug8')

    cy.get('tr:nth-of-type(3) td:nth-of-type(3) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '9')
      .and('have.attr', 'data-label', 'Sep9')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Sep9')

    cy.get('tr:nth-of-type(4) td:nth-of-type(1) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '10')
      .and('have.attr', 'data-label', 'Oct10')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Oct10')

    cy.get('tr:nth-of-type(4) td:nth-of-type(2) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '11')
      .and('have.attr', 'data-label', 'Nov11')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Nov11')

    cy.get('tr:nth-of-type(4) td:nth-of-type(3) button')
      .should('not.have.attr', 'aria-selected', 'true')
      .and('have.attr', 'tabindex', '-1')
      .and('have.attr', 'data-value', '12')
      .and('have.attr', 'data-label', 'Dec12')
      .and('not.have.class', 'usa-date-picker__calendar__month--selected')
      .and('not.have.class', 'usa-date-picker__calendar__month--focused')
      .and('contain', 'Dec12')
  })

  it('emits `activeMonth` and `selectorMode` prop values', () => {
    cy.mount(UsaDatePickerCalendarMonth, {
      props: {
        activeDate: '2022-08-15',
        monthLabels: MONTH_LABELS,
        minDate: MIN_DATE,
        maxDate: MAX_DATE,
      },
    })
      .its('wrapper')
      .as('wrapper')

    cy.get('@wrapper')
      .vue()
      .then(vm => {
        const emitted = vm.emitted()
        expect(emitted).to.not.have.property('update:selectorMode')
        expect(emitted).to.not.have.property('update:activeMonth')
      })

    cy.get('button[data-value="11"').click()

    cy.get('@wrapper')
      .vue()
      .then(vm => {
        const emitted = vm.emitted()
        expect(emitted).to.have.property('update:selectorMode')
        expect(emitted).to.have.property('update:activeMonth')

        const currentSelectorModeEvent = vm.emitted('update:selectorMode')
        const currentActiveMonthEvent = vm.emitted('update:activeMonth')

        expect(currentSelectorModeEvent).to.have.length(1)
        expect(currentSelectorModeEvent[0]).to.contain('day')

        expect(currentActiveMonthEvent).to.have.length(1)
        expect(currentActiveMonthEvent[0]).to.contain(11)
      })
  })
})
