name: Docs

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run build-storybook

      - name: Disable Jekyll builder
        run: touch ./storybook-static/.nojekyll

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: storybook-static
          target-folder: docs
          # Remove previous build files.
          clean: true
          # Do not remove the `.nojekyll` file.
          clean-exclude: |
            .nojekyll
